"""
@file src/protocol/__init__.py
@brief 串口协议工具包
"""

from protocol.frame import (
    FRAME_BODY_SIZE,
    FRAME_HEAD,
    FRAME_SIZE,
    MODE_ACK,
    MODE_TCP,
    MODE_UDP,
    decode_frame,
    encode_frame,
)
from protocol.topic import (
    ROLE_ASSISTANT,
    ROLE_MASTER,
    TOPIC_ASSISTANT_EVENT_REPORT,
    TOPIC_ASSISTANT_FEEDFORWARD_VELOCITY,
    TOPIC_ASSISTANT_STATE_SYNC,
    TOPIC_ASSISTANT_VISION_EVENT_REPORT,
    TOPIC_ASSISTANT_VISION_TASK_SYNC,
    TOPIC_LOCAL_VISION_VELOCITY,
    TOPIC_MASTER_VISION_EVENT_REPORT,
    TOPIC_MASTER_VISION_HOOK_SYNC,
    TOPIC_VISION_OBSERVATION,
    UART6,
    UART8,
    can_role_read,
    can_role_write,
    get_topic_entry,
    get_topic_spec,
    validate_body_bytes,
    validate_mode_for_topic,
    validate_port_for_topic,
)
from protocol.transport import create_transport

__all__ = [
    "FRAME_BODY_SIZE",
    "FRAME_HEAD",
    "FRAME_SIZE",
    "MODE_ACK",
    "MODE_TCP",
    "MODE_UDP",
    "decode_frame",
    "encode_frame",
    "ROLE_ASSISTANT",
    "ROLE_MASTER",
    "TOPIC_ASSISTANT_EVENT_REPORT",
    "TOPIC_ASSISTANT_FEEDFORWARD_VELOCITY",
    "TOPIC_ASSISTANT_STATE_SYNC",
    "TOPIC_ASSISTANT_VISION_EVENT_REPORT",
    "TOPIC_ASSISTANT_VISION_TASK_SYNC",
    "TOPIC_LOCAL_VISION_VELOCITY",
    "TOPIC_MASTER_VISION_EVENT_REPORT",
    "TOPIC_MASTER_VISION_HOOK_SYNC",
    "TOPIC_VISION_OBSERVATION",
    "UART6",
    "UART8",
    "can_role_read",
    "can_role_write",
    "get_topic_entry",
    "get_topic_spec",
    "validate_body_bytes",
    "validate_mode_for_topic",
    "validate_port_for_topic",
    "create_transport",
]
